apiVersion: v1
kind: Secret
metadata:
  name: logstash-secret
type: Opaque
stringData:
  LOGSTASH_USER: "logstash"
  LOGSTASH_PASSWORD: "7@qYfx&psj__UQ-MFh9_$!DxmntFl45W"
  LOGSTASH_KEYSTORE_PASS: "XTbrM971"
