apiVersion: v1
kind: Secret
metadata:
  name: kibana-secret
type: Opaque
stringData:
  KIBANA_USER: "kibana"
  KIBANA_PASSWORD: "CJiEq3Yi!_js6Tnpu3txGa3LPEbAG4T!"
  KIBANA_SYSTEM_USER: "kibana_system"
  KIBANA_SYSTEM_PASSWORD: "S0L!4LPs3x!qJUN_LaW_EYxx72!GAQaD"
  ELASTICSEARCH_USER: "elastic"
  ELASTICSEARCH_PASSWORD: "13fvDtPOgzir_dw8qvde60EkA4LBEKM!1"

