apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  ELK_VERSION: "8.15.1"
  KIBANA_IMAGE: "elk/kibana-elk:8.15.1"
  KIBANA_BUILT_IMAGE: "elk/kibana-elk:built"
  KIBANA_HOST: "kibana"
  KIBANA_PORT: "5601"
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  KIBANA_P12: "/usr/share/kibana/config/certs/kibana.p12"
  KIBANA_CACERT: "/usr/share/kibana/config/certs/ca.crt"
  KIBANA_CERT: "/usr/share/kibana/config/certs/kibana.crt"
  KIBANA_KEY: "/usr/share/kibana/config/certs/kibana.key"
  KIBANA_ENCRYPTION_KEY: "mn8Zm5jv!mS3FXz7mI2qtR3w8NaS_Ld2"
