apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
type: Opaque
stringData:
  ELASTIC_PASSWORD: "13fvDtPOgzir_dw8qvde60EkA4LBEKM!1"
  LOGSTASH_PASSWORD: "7@qYfx&psj__UQ-MFh9_$!DxmntFl45W"
  KIBANA_SYSTEM_PASSWORD: "S0L!4LPs3x!qJUN_LaW_EYxx72!GAQaD"
  KIBANA_PASSWORD: "CJiEq3Yi!_js6Tnpu3txGa3LPEbAG4T!"
  KEYSTORE_PASSWORD: "XTbrM971"
