apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: ${REGISTRY_HOST}:30500/${KIBANA_BUILT_IMAGE}
        ports:
        - containerPort: 5601
          name: http
        envFrom:
        - configMapRef:
            name: kibana-config
        env:
        - name: KIBANA_USER
          valueFrom:
            secretKeyRef:
              name: kibana-secret
              key: KIBANA_USER
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kibana-secret
              key: KIBANA_PASSWORD
        - name: KIBANA_SYSTEM_USER
          valueFrom:
            secretKeyRef:
              name: kibana-secret
              key: KIBANA_SYSTEM_USER
        - name: KIBANA_SYSTEM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kibana-secret
              key: KIBANA_SYSTEM_PASSWORD
        - name: KIBANA_CERT
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: KIBANA_CERT
        - name: KIBANA_ENCRYPTION_KEY
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: KIBANA_ENCRYPTION_KEY
        - name: KIBANA_KEY
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: KIBANA_KEY
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: kibana-secret
              key: KIBANA_SYSTEM_USER
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kibana-secret
              key: KIBANA_SYSTEM_PASSWORD
