apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-config-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: es-config
        image: ${REGISTRY_HOST}:30500/${ELASTIC_BUILT_IMAGE}
        command: ["/usr/local/bin/es_build.sh"]
        args:
          - "$(ELASTIC_PASSWORD)"
          - "$(LOGSTASH_PASSWORD)"
          - "$(KIBANA_SYSTEM_PASSWORD)"
          - "$(KIBANA_PASSWORD)"
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: ELASTIC_PASSWORD
        - name: LOGSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: LOGSTASH_PASSWORD
        - name: KIBANA_SYSTEM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: KIBANA_SYSTEM_PASSWORD
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: KIBANA_PASSWORD
        - name: ELASTIC_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: ELASTIC_CLUSTER_NAME
        - name: ELASTIC_NODE_NAME
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: ELASTIC_NODE_NAME
        - name: ELASTIC_P12
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: ELASTIC_P12
        - name: ELASTIC_TRUST_P12
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: ELASTIC_TRUST_P12
        - name: KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: KEYSTORE_PASSWORD
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      restartPolicy: Never
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
